### ISSUE TITLE
Any plans for Firefox?

### ISSUE THREAD

**Issue by gliu20** [teresa-ou/inboxy#10]
Your extension can be easily ported to Firefox; most apis are completely compatible without any code changes.

**Comment by teresa-ou** [comment]
I can probably start looking into this later this week!

**Comment by gliu20** [comment]
Awesome! Looking forward to it as a big firefox user myself!

**Comment by gliu20** [comment]
I just test the extension on Firefox! It seems to work. I guess the only thing you need to do is sign up for an account on the Firefox developer hub: https://addons.mozilla.org/en-US/developers/addons and add a submission by zipping your dist extension directory (making sure the archive doesn't have a root folder in it).

So the archive should look like this
```
archive
|__icons
|__blah blah files
|__manifest.json
```
if the file structure is like this you might get an error (at least that's what happened when i made firefox addons in 2018)
```
archive
|__dist
      |__icons
      |__blah blah
      |__manifest.json
```

**Comment by teresa-ou** [comment]
Cool! I didn't realize how similar it would be between Chrome and Firefox. 

So far, I noticed that on Firefox, the image assets aren't appearing and there is some vertical shifting happening, so I'll look into fixing that.

**Comment by teresa-ou** [comment]
I've made a few changes and submitted the extension to Firefox. If it gets approved, I'll close this issue.

**Comment by gliu20** [comment]
Awesome! Thanks so much for doing this!

**Comment by teresa-ou** [comment]
No problem! It's available now at https://addons.mozilla.org/en-US/firefox/addon/inboxy-inbox-bundles-for-gmail/

**Comment by benoror** [comment]
Hi! Firefox is first-class on the maintained fork. **Inbundly** is on Firefox Add-ons as well as the Chrome Web Store.

Firefox: https://addons.mozilla.org/firefox/addon/inbundly/
Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Site: https://inbundly.com/
