### ISSUE TITLE
Word-wrap + Distinction between Bundle VS Email

### ISSUE THREAD

**Issue by vtexperts** [teresa-ou/inboxy#11]
1. I noticed the bundle name will now word-wrap if it doesn't fit into 168px.
perhaps increase the width?  or dont break? 

2. Its hard to differentiate between bundle and email row.

Here's what I see:
![chrome_2020-03-31_13-24-43 1](https://user-images.githubusercontent.com/17834854/78061791-57c17f00-7353-11ea-8e40-190eec187f52.png)

---
I just wanted you to be aware of it and take action if needed.

I have a workaround by using custom css style, which looks like this:
![chrome_2020-03-31_13-34-43 1](https://user-images.githubusercontent.com/17834854/78062535-7116fb00-7354-11ea-8638-82fec57dd023.png)

**Comment by teresa-ou** [comment]
The 168px width comes from Gmail's css for the sender for emails. 

However, I agree that the width could probably be increased. This can be done without pushing the next column to the right, i.e. just reduce the padding between bundle name and the list of senders. The bundle name would still wrap if it exceeds that new width. 

I think reducing the width of the subject + email preview would hide part of the info shown in that column. If the width is a fixed amount, it would result in a lot of unused blank space for users who mostly have emails that aren't in bundles.

As for the distinction between bundle and email rows, I will open a separate issue for that.

**Comment by teresa-ou** [comment]
I've increased the width from 168px to 188px in [v1.3.0](https://github.com/teresa-ou/inboxy/releases/tag/v1.3.0), as described in my previous comment.
