### ISSUE TITLE
Issues with latest Chrome or Gmail?

### ISSUE THREAD

**Issue by tmenier** [teresa-ou/inboxy#114]
Hi! Been using this for probably a year or so and loving it. But few days ago my bundles just disappeared completely, and everything looks as if the extension isn't installed at all. Tried uninstalling/reinstalling the extension. Tried incognito to make sure another extension wasn't interfering. Tried restarting my computer. Tried new and old Gmail view. Made sure I'm on default density and default inbox type. Sadly no luck. I'm on latest Chrome/Windows.

My best guess was some recent update to Gmail or Chrome might be the culprit (It may have coincided with the last time I updated Chrome, but not 100% certain.) But I would have expected to see others bring up the issue too, so is it just me? Is there any sort of standard troubleshooting list I could go through to make sure I'm not missing something?

Thanks in advance, love the extension!

**Comment by adamistic** [comment]
On Windows here, using chrome-based Brave browser and having the same experience...

**Comment by securesecure** [comment]
I'm having the same issue on windows with Chrome browser starting this morning and coinciding with Gmail introducing a new look. (both original and new look don't seem to work with inboxy)

**Comment by lpakula** [comment]
Same for me, ubuntu 20.04 with Chrome browser.

@teresa-ou is this project still maintained?

**Comment by securesecure** [comment]
how do we implement vcaen's fix?

**Comment by awreccan** [comment]
Can someone who knows how to please package @vcaen's #112 fix so that we can use it while we await its merge and release through the chrome webstore? 🙏🏼

**Comment by vcaen** [comment]
Probably only Teresa has access to the developer console.
I can package it under another name on the chrome web store if Teresa
doesn't update it.

**Comment by securesecure** [comment]
@vcaen you would be my hero if you did so

**Comment by lpakula** [comment]
I've done the fork, built the package and loaded the "unpacked extension" locally for the time being
https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked

This is the fork: 
https://github.com/lpakula/inboxy

You can clone it and build locally
https://github.com/lpakula/inboxy#setup

Fork includes: 

- https://github.com/teresa-ou/inboxy/pull/112 
- https://github.com/teresa-ou/inboxy/pull/99
- https://github.com/teresa-ou/inboxy/pull/71 (it requires enabling the "select all" feature in the options to layout nicely) 

I hope it can all get into the main project soon

**Comment by awreccan** [comment]
@lpakula Could you zip it and share it via Google Drive, or via Github's publish/release flow? 🙏🏼

**Comment by lpakula** [comment]
There you go

https://github.com/lpakula/inboxy/releases/tag/v0.0.9

**Comment by jasonpartin** [comment]
> There you go
> 
> https://github.com/lpakula/inboxy/releases/tag/v0.0.9

Thanks but unfortunately,  I don't think we can install CRX files directly anymore.
![chrome-crx](https://user-images.githubusercontent.com/29963380/185700474-99ba7bad-342c-4c2e-9146-535d34b636e8.png)

[More info](https://developer.chrome.com/docs/extensions/mv3/external_extensions/)

**Comment by lpakula** [comment]
@jasonpartin if you can install crx download and extract the zip package and install it as an unpacked extension (dist folder)
https://github.com/lpakula/inboxy/archive/refs/tags/v0.0.9.zip

How to install unpacked extensions
https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked

**Comment by jasonpartin** [comment]
> @jasonpartin if you can install crx download and extract the inboxy.zip package and install it as an unpacked extension https://github.com/lpakula/inboxy/releases/download/v0.0.9/inboxy.zip
> 
> How to install unpacked extensions https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked

Hmm.. when I try to load the unpacked extension, I receive this error. I'm using Brave, maybe that's the problem?
![unpacked-error](https://user-images.githubusercontent.com/29963380/185703539-f53d6dc7-ff14-4489-a6c7-63449dac6d8a.png)

**Comment by lpakula** [comment]
@jasonpartin i put the wrong link to the zip file. 
Please download again from the new link

**Comment by jasonpartin** [comment]
@lpakula Thank you so very much! I have my beloved bundles back! 👍
![inboxy-unofficial](https://user-images.githubusercontent.com/29963380/185706268-c267da73-4189-4af3-af73-1f7d72d99bc0.png)

**Comment by awreccan** [comment]
Installed as an unpacked extension, bundles are back! Thank you so much, inbox is clean again!

But there are 2 "star toggles" on the top right
![image](https://user-images.githubusercontent.com/10543509/185713343-59623e25-01cf-429f-b810-0ae00cbcc844.png)

And the bundles are aligned too much to the left:
![image](https://user-images.githubusercontent.com/10543509/185713444-b90155da-cd2a-4134-8435-8912fa4d5d5a.png)



FYI, Chrome doesn't allow downloading the .crx file, it shows this error
<img width="472" alt="image" src="https://user-images.githubusercontent.com/10543509/185713263-ac440175-e03d-4f5f-b776-ff7e937cddc9.png">

**Comment by lpakula** [comment]
@awreccan you need to enable 'select all'  feature in the options to fix the alignment

**Comment by jasonpartin** [comment]
> But there are 2 "star toggles" on the top right ![image](https://user-images.githubusercontent.com/10543509/185713343-59623e25-01cf-429f-b810-0ae00cbcc844.png)
> 

I also have the duplicate toggles.

**Comment by lpakula** [comment]
I released a new version to address two issues
- duplicated star toggle
- incorrect indentation without "select all" option

https://github.com/lpakula/inboxy/releases/tag/v0.0.10

**Comment by abbynoyce** [comment]
Thanks @lpakula! This thread popped right up when I came looking for any updates (I went on vacation for a week, and my bundles were BROKEN when I got back!) and the unofficial release is working like a charm. Appreciate it!

**Comment by jasonpartin** [comment]
Thanks @lpakula!

**Comment by dbieler** [comment]
Thank you fixing @lpakula - very much appreciated. I am seeing one weird bug - after I open a bundle and select a message within that bundle, the bundle collapses and I can't go to the next message in the bundle without reopening it. Anyone else seeing this, or any ideas how to address?

**Comment by teresa-ou** [comment]
Hi all, thank you for your patience, and big thank you to @vcaen and @lpakula!

I will be merging #112 shortly. Before releasing to the Chrome store, I will make a few additional adjustments so that bundles aren't shown in search results and some other pages. Unfortunately, I can't reproduce the main bug that's being discussed here (bundles disappeared) in any of my accounts, with either the original or new Gmail views.

Lastly, this project is no longer being actively maintained. I do however intend to keep the extension functional at a basic level. I will be updating the README and site to reflect this.

**Comment by teresa-ou** [comment]
v1.6.2 has been submitted to Chrome webstore, pending approval. It includes the following:

- #112, with adjustments to limit bundles to just the pages where it was previously active
- makes the archive button in the top menu a checkmark again
- unread messages will be white instead of grey when using a light-colored theme

**Comment by teresa-ou** [comment]
> Thank you fixing @lpakula - very much appreciated. I am seeing one weird bug - after I open a bundle and select a message within that bundle, the bundle collapses and I can't go to the next message in the bundle without reopening it. Anyone else seeing this, or any ideas how to address?

@dbieler It does look like others are seeing this issue too: https://github.com/vcaen/inboxy/issues/1. I'll have to look into it a bit more. I have some ideas about how to fix it, but I can't be sure that it won't reintroduce the original issue of bundles not working entirely (since I don't have a way to reproduce that).

**Comment by vtexperts** [comment]
> I'll have to look into it a bit more. I have some ideas about how to fix it, but I can't be sure that it won't reintroduce the original issue of bundles not working entirely (since I don't have a way to reproduce that).

@teresa-ou - I too did not have this problem until just a few days ago, but apparently it stopped working 12 days ago (or more). 

To reproduce the issue, you will need to clear "site data" for *.google.com.

1. Open Chrome Settings
2. Hit "Clear all data". This will basically clear cache and log you out. It does **NOT** clear passwords, history, etc...

![clear_site_data_314O1O075f8b7W7u3T6r](https://user-images.githubusercontent.com/17834854/186406341-e03ff3b5-b383-4ef1-a30c-6141a319b82c.gif)

**Comment by dbieler** [comment]
@teresa-ou see here:https://github.com/teresa-ou/inboxy/issues/118#issuecomment-1225716657
I think the collapsing is somehow tied to the Preview Pane/Mark Read behavior.

**Comment by teresa-ou** [comment]
@vtexperts Thanks for the tip. I tried clearing the data though and still didn't get the bug. 

Since the main bug is fixed, I will close this and use #118 to track the collapsing issue.

**Comment by benoror** [comment]
Hi! The 2022 "bundles vanished" wave led to upstream Manifest V3 / rebundle work. Ongoing maintenance is on **Inbundly** (GPL-3.0 fork of Teresa Ou's inboxy), published for Chrome and Firefox with fixes through v4.3.0.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Firefox: https://addons.mozilla.org/firefox/addon/inbundly/
Site: https://inbundly.com/
Issues: https://github.com/benoror/inbundly/issues

**Comment by jasonpartin** [comment]
> Hi! The 2022 "bundles vanished" wave led to upstream Manifest V3 / rebundle work. Ongoing maintenance is on **Inbundly** (GPL-3.0 fork of Teresa Ou's inboxy), published for Chrome and Firefox with fixes through v4.3.0.
> 
> Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga Firefox: https://addons.mozilla.org/firefox/addon/inbundly/ Site: https://inbundly.com/ Issues: https://github.com/benoror/inbundly/issues

Hey Ben! Thanks for picking this up and keeping it maintained! Installed and it's working great! Thank you!

**Comment by benoror** [comment]
> > Hi! The 2022 "bundles vanished" wave led to upstream Manifest V3 / rebundle work. Ongoing maintenance is on **Inbundly** (GPL-3.0 fork of Teresa Ou's inboxy), published for Chrome and Firefox with fixes through v4.3.0.
> > Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga Firefox: https://addons.mozilla.org/firefox/addon/inbundly/ Site: https://inbundly.com/ Issues: https://github.com/benoror/inbundly/issues
> 
> Hey Ben! Thanks for picking this up and keeping it maintained! Installed and it's working great! Thank you!

Amazing! ❤️
