### ISSUE TITLE
Inboxy suddenly stopped working for me too, and it looks like that project hasn't been active in quite some time. Bummer, I really liked it. Here's another alternative that's free and works great for me so far (no affiliation to me):

### ISSUE THREAD

**Issue by securesecure** [teresa-ou/inboxy#115]
Inboxy suddenly stopped working for me too, and it looks like that project hasn't been active in quite some time. Bummer, I really liked it. Here's another alternative that's free and works great for me so far (no affiliation to me):

https://chrome.google.com/webstore/detail/inbox-reborn-theme-for-gm/bkphmihkdbdgedlaflnkhnmnmibffomf

_Originally posted by @tmenier in https://github.com/teresa-ou/inboxy/issues/102#issuecomment-1214168998_

**Comment by tmenier** [comment]
@securesecure I'm not sure if this was a mistake or what but please delete this issue. I already described the issue in #114, and I don't think there was a need to lift a multi-sentence comment of mine from one issue and use it as the title of another. Thanks.

**Comment by securesecure** [comment]
duplicate by mistake

**Comment by tmenier** [comment]
Thank! I was hoping that's all it was and not some strange way to send a message 🤣
