### ISSUE TITLE
Problems with new Gmail view

### ISSUE THREAD

**Issue by awreccan** [teresa-ou/inboxy#116]
Gmail has a new view. There are some problems with this that I've noticed so far:

1. The archive button on the top bar isn't transforming into a done button anymore. However, the archive button that appears when hovering over an email in the emails list _does_ transform into a done button as usual.
![image](https://user-images.githubusercontent.com/10543509/185279763-cbb68b51-f605-46b7-ad71-46edb23c8ba7.png)

2. Bundle background colour: When you expand a bundle we expect a grey bundle background that's different from other gmail colours (unread email background, read email background, page's white background):
![image](https://user-images.githubusercontent.com/10543509/185278831-38808f66-ddbf-4974-a7fd-b63aa949cc50.png)
(from https://www.inboxymail.com/assets/screenshot-bundle@2x.png)
But with the new view, the background colour of the bundle makes it very hard to differentiate a bundle from non-bundles, and bundle from unread email. And if you're using the dark theme, it makes a bundle with unread emails look quite ugly too:
![Screenshot 2022-08-18 at 10 34 01](https://user-images.githubusercontent.com/10543509/185280347-d4e9e835-9c5a-4378-8c10-85a5f2f92851.png)

**Comment by teresa-ou** [comment]
Thanks for letting me know @awreccan! 

The first item is fixed in v1.6.2, pending Chrome store approval. I plan to fix the second item for the colors in the next version, likely in the next week or so.

**Comment by teresa-ou** [comment]
New set of colors coming in v1.6.3. One thing to note: although Gmail lets users switch back to the old view, I won't be supporting the old Gmail view for inboxy.

**Comment by vtexperts** [comment]
Well, that explains why my colors are off - ha! I guess I'll switch to new gmail view.

**Comment by benoror** [comment]
Hi! Gmail view chrome keeps moving. Please try **Inbundly** latest; if Done/Archive toolbar transforms still misbehave, open a bug with "new vs old" view notes.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new
