### ISSUE TITLE
Bundles collapses after archiving a single message. [Due to Recent Update]

### ISSUE THREAD

**Issue by vtexperts** [teresa-ou/inboxy#118]
The newly released version (Aug 24th) has a rather annoying bug - the bundle collapses as soon as you archive a message within the bundle.

Please see the video below. 
_My gmail interface has a slightly different look and feel (injected CSS changes only), but regardless of my .css - the issue exists on "plain" gmail as well._

![inboxy_bundle_collapsing_after_archive_8Y3M378O2s4H441e4B4h](https://user-images.githubusercontent.com/17834854/186404071-325bc6aa-1405-4543-80fa-cdb0ac813f87.gif)

**Comment by dbieler** [comment]
It seems to be tied to the Preview Pane/Mark Read behavior. It goes away if you turn the feature off, and the collapsing happens exactly when the timer in Gmail is set to mark the conversation as "read":
![image](https://user-images.githubusercontent.com/59615663/186428759-2b9cb942-7010-4cd9-9b02-cc251fe46203.png)

**Comment by vtexperts** [comment]
It appears that the **bundle gets collapsed on every action taken on the message** (start, label as, mark as unread, etc...).

![0Z0i3P2I8d2h720t7t8Z](https://user-images.githubusercontent.com/17834854/186506919-e2b907d7-7af4-4361-80b8-3b9e42500f72.gif)

**Comment by teresa-ou** [comment]
I think I have a relatively safe solution that won't reintroduce #114 -- but if you see a regression in v1.6.3 once that's out, please let me know.

**Comment by teresa-ou** [comment]
Update: I've just now started seeing #114 with v1.6.1 in one of my accounts, so I'm fairly confident that v1.6.3 will not cause a regression.

**Comment by lpakula** [comment]
@vtexperts sorry for off-topic, but how did you manage to create custom categories (Customers, CRM etc.)?

**Comment by dbieler** [comment]
1.6.3 just rolled to me and all is well with the Inboxy world once again. Thank you thank you @teresa-ou

**Comment by benoror** [comment]
Hi! Collapsing on archive inside a bundle was addressed in **Inbundly** v4.1.0 (open bundle stays put while you work). Please try the latest build.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Site: https://inbundly.com/
