### ISSUE TITLE
firefox addon out of date

### ISSUE THREAD

**Issue by trapier** [teresa-ou/inboxy#120]
Greetings!

Just an FYI that whereas the latest release is 1.6.3, https://addons.mozilla.org/en-US/firefox/addon/inboxy-inbox-bundles-for-gmail/ is still on 1.6.1.

**Comment by trapier** [comment]
Looks like this would be blocked by [the recent bump to manifest v3](https://github.com/teresa-ou/inboxy/pull/112/commits/bf6417acada80a74ab14522bb90a9b32b3c1a8cc), which isn't yet supported by Firefox.

Attempting to load release 1.6.3 after [enabling developer preview of manifest v3 in Firefox](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/) resulted in error `background.service_worker is currently disabled`, which seems to be expected behavior per the [Mozilla blog](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/) (emphasis mine):

> In Firefox, we have decided to support Event Pages in MV3, and **our developer preview will not include Service Workers** (we’re continuing to work on supporting these for a future release).

**Comment by teresa-ou** [comment]
Thanks for letting me know! 

I have created a separate branch for firefox which will use manifest v2. 1.6.3 has also been submitted to Firefox Add-ons.

**Comment by benoror** [comment]
Hi! For a current Firefox build, use **Inbundly** on AMO (upstream inboxy listing may lag).

Firefox: https://addons.mozilla.org/firefox/addon/inbundly/
Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Site: https://inbundly.com/
