### ISSUE TITLE
View all shows no emails for nested label

### ISSUE THREAD

**Issue by teresa-ou** [teresa-ou/inboxy#14]
The search is something like "label:Inbox and label:Work", but it should probably be "label:Inbox label:Work"

**Comment by teresa-ou** [comment]
Fixed in [v1.3.0](https://github.com/teresa-ou/inboxy/releases/tag/v1.3.0)

**Comment by benoror** [comment]
Hi! If **View all** on a nested label still builds a bad search, please retest on **Inbundly** and open a bug with the label path. Ampersand cases were also reported historically (#44).

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new
