### ISSUE TITLE
Feature Request: Toggle Show/Hide Bundles

### ISSUE THREAD

**Issue by krejko** [teresa-ou/inboxy#17]
For starters, thank you so much for this plugin! It has already transformed how I organize my digital life. 

There is, however, one feature that would take this to the next level for me. I was curious if it would be possible to add a toggle on a label to determine if the associated bundle gets shown in the inbox or not. Something similar to the 'Bundle messages in the inbox' feature that was previously in Inbox: https://lifehacker.com/control-when-and-if-bundles-appear-in-gmails-new-inbox-1661162667

I have a lot of labels in my Gmail. Many emails I receive automatically get assigned to multiple labels so I can easily find them based on the context. For these messages, I see two or more different bundles in the inbox view, each that has the same one new message. It would be great if I could keep the labels but toggle off the 'bundle' feature for some of them so only one bundle shows in the inbox view. 

It would be a game-changer for me if something like this would be possible. Thanks again for all your hard work on this!

**Comment by teresa-ou** [comment]
I'm glad you're enjoying inboxy. Thanks for your suggestion! I think this should be possible, and this feature would be useful for many people, too. I'll look into it!

**Comment by vtexperts** [comment]
I believe all you have to do is set "hide" in the message list. Those labels are not converted to bundles if "hidden". 

![chrome_2020-04-05_15-38-14 1](https://user-images.githubusercontent.com/17834854/78509465-a441fb80-7753-11ea-9ea1-881ff325ce24.png)

**Comment by teresa-ou** [comment]
Thanks for the tip! That would certainly come in handy if you just want to turn off bundling for a few labels.

There are a couple cases where this might not be enough, although I'm not sure how common these will be:

1. The label won't be visible in the inbox. So when you're in the inbox, you can't tell if the label was applied (ex. by a filter) and you would like to have that information readily available.
2. If you have a large number of labels and want to opt in to bundling for just a few of them, you would have to click "hide" for each label from Gmail Settings.

**Comment by krejko** [comment]
@vtexperts, Super helpful tip. You are right that this is a completely workable solution according to exactly what I was asking for. Although as @teresa-ou points out while putting this solution into place, I did also notice that all of the labels and color-coding in nested labels and the inbox did disappear.   For me, personally, missing labels is still a better option than seeing multiple bundles, but in a perfect world we wouldn't have to choose between these two options.

**Comment by teresa-ou** [comment]
I've added an options page where you can list labels to exclude/include from bundling (v1.5.0).

**Comment by benoror** [comment]
Hi! Per-label "bundle or not" eyeballs are not in the inbox UI. **Inbundly** has include/exclude lists, priority rules, and a **master bundling on/off switch**.

If you want one-click per-label hide, open a feature request.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new
