### ISSUE TITLE
Color issue on Dark themes

### ISSUE THREAD

**Issue by dferrantino1** [teresa-ou/inboxy#26]
Unread messages on Dark theme are using a white-on-white color scheme. Refreshing the page or disabling/enabling Inboxy does not resolve.

Issue:
![image](https://user-images.githubusercontent.com/64145902/79987411-5fb89e80-847b-11ea-8955-86d2334ae6ac.png)

Default w Inboxy turned off:
![image](https://user-images.githubusercontent.com/64145902/79987529-88d92f00-847b-11ea-8325-d1ae0e9b6881.png)

**Comment by teresa-ou** [comment]
Thanks for letting me know! I have fixed this in the latest version, 1.4.1, which has been published to the Chrome store now (it will also be released to Firefox later today).

**Comment by dferrantino1** [comment]
New version looks good, thanks!

**Comment by benoror** [comment]
Hi! Light/dark Gmail theme matching is a focus area in **Inbundly**, along with label-color fills that stay readable.

Please try the latest build; if unread rows still go white-on-white, open a bug with theme details.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new
