### ISSUE TITLE
"Today" label changes when a snoozed email arrives

### ISSUE THREAD

**Issue by adamistic** [teresa-ou/inboxy#31]
I had an email that arrived yesterday, and today I wanted it at the top of my inbox for easy access/to remind me of a thing I need to do soon, so I snoozed it to arrive a few minutes later.

Before the snooze time, my inbox had headings **Today, Yesterday, This month**.  After the snooze time was reached, the email appeared in my inbox at the top (it was starred) and then my inbox had headings **Yesterday, Yesterday, This month**.

I also tried this when my email was not starred; in that case the label that it belongs in moved to the top of my inbox when the snooze time was reached, as expected, but still the headings were *Yesterday, Yesterday, This month**.

Also, I wanted to mention that this extension is a lifesaver.  Honestly, after using Google Inbox for over a year it's like it broke my email brain; I could no longer scan a long list of independent emails and reasonably process them, so since Google Inbox was retired I've been struggling to _mostly_ notice what I needed to in my inbox (occasionally missing things it would be best not to miss), where now with inboxy I can again deal with my inbox sanely, easily, with no stress.  Thank you!!

**Comment by adamistic** [comment]
Moments after I posted the above, a new email arrived and now my headings are **Today, Yesterday, Yesterday, This month**.  
Screenshot:  https://imgur.com/sJPgMZe

**Comment by adamistic** [comment]
P.S.  I realize I have a ton of email in my inbox; I was actually letting it stack up for days so that I could illustrate to someone else the difference inboxy makes between a huge list of individual messages vs bundles.  So it was in this context (plus use of the snooze feature) that I noticed issues with the time-based headings.

**Comment by teresa-ou** [comment]
Thanks for bringing this to my attention! 

I hadn't noticed since I personally don't use the snooze feature. But I'm sure many former Inbox users do use snooze, so I'm planning to release a fix for this in the next week or so.

I'm glad to hear that inboxy is helping you with managing email. I definitely relate with that overwhelming feeling of getting too many emails and missing the important ones!

**Comment by teresa-ou** [comment]
This is fixed in v1.4.2. 

There isn't a way to detect what time a message reappears after it was snoozed, so it will just belong to the same date section as the previous non-snoozed message.
