### ISSUE TITLE
The hover styling for a bundle looks off at narrow widths

### ISSUE THREAD

**Issue by GreenGremlin** [teresa-ou/inboxy#36]
Specifically, with the preview pane enabled and the message list width as small as possible, I see this when hovering a bundle:

![image](https://user-images.githubusercontent.com/647452/82590346-686fc380-9b52-11ea-8a12-4dcb93cd1528.png)

It looks like the more narrow width causes the time to wrap to a new line. This isn't too high priority of an issue, since expanding the list slightly fixes the issue. But, it's probably a simple css update to fix it.

**Comment by teresa-ou** [comment]
Thanks for pointing this out! It will probably get fixed in the next release.

**Comment by teresa-ou** [comment]
Fixed in v1.5.1. 

In #11, I arbitrarily increased the width of element for the label name to 188px, which caused this. So I decreased it to 180px now.
