### ISSUE TITLE
Feature Request: User Styles (CSS)

### ISSUE THREAD

**Issue by vtexperts** [teresa-ou/inboxy#39]
A low hanging fruit would be to allow users to add custom CSS styles.

I personally use stylus just so I can inject .css to slightly alter the look and feel, however being able to add the style into the extension options would be more convenient. 

Also, the users would like share their personalized styles, which would increase inboxy value.

Here's a good example - it's just few lines of pure .css code, but it makes gmail folder list more pleasant (at least for me).

# BEFORE and AFTER
![b](https://user-images.githubusercontent.com/17834854/83326099-d1cc9200-a236-11ea-86cf-73760d853410.png)

**Comment by teresa-ou** [comment]
Although this would be easy to implement, I think allowing custom css styles goes beyond the scope of what inboxy should do, i.e. the main function is providing bundles, not changing the look of Gmail. In addition, there are already more powerful extensions that allow custom css on any page, not just Gmail.

**Comment by teresa-ou** [comment]
Closing this, since I don't anticipate adding this feature.

**Comment by benoror** [comment]
Hi! Inbundly does not embed a custom CSS editor. Stylus still works, but class/vars were renamed in the v4 rebrand: `.inbundly` / `--inbundly-*` (see NOTICE / changelog).

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Repo: https://github.com/benoror/inbundly
