### ISSUE TITLE
Feature Request:  Show last email date/sender in the grouping. 

### ISSUE THREAD

**Issue by vtexperts** [teresa-ou/inboxy#4]
Currently, the grouping is very simple, which is great! 

It would be nice to see the last email date/sender at the far right side (when collapsed). 

Example: "_2 hours ago from **John Smith**_"

I'm attaching a screenshot.
![chrome_2020-03-29_08-39-21 1](https://user-images.githubusercontent.com/17834854/77850572-1c7b5080-7199-11ea-8164-a593fd92518f.png)

**Comment by teresa-ou** [comment]
This is now fixed in v1.2.0. See #6 which is related.

**Comment by benoror** [comment]
Hi! Quick note from the maintained fork: **Inbundly** continues Teresa Ou's inboxy under GPL-3.0.

Collapsed bundles still show a compact sender preview; a richer "2 hours ago from Jane" trailing meta line is not a dedicated feature yet. If you still want that, please open a request on https://github.com/benoror/inbundly/issues/new.

Shipping nearby: **label colors**, **snooze whole bundle**, **select-all**.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
