### ISSUE TITLE
Do not separate emails by date

### ISSUE THREAD

**Issue by espiler** [teresa-ou/inboxy#43]
Is it possible to activate this extension without having it separate my emails by date? It does a great job at bundling, but has expanded my inbox because of the separation of TODAY, THIS MONTH, and EARLIER. I would prefer  it if I could choose not to separate emails by date at all.

In these before/after photos, you can see that my inbox size has not changed even though the extension bundled 4 emails 
<img width="618" alt="Screen Shot 2020-06-15 at 8 57 04 AM" src="https://user-images.githubusercontent.com/7787374/84679718-81b42780-aee6-11ea-8fd7-887fe6180a81.png">
<img width="624" alt="Screen Shot 2020-06-15 at 8 57 38 AM" src="https://user-images.githubusercontent.com/7787374/84679722-824cbe00-aee6-11ea-881a-0d0cdcf9b0c3.png">

**Comment by teresa-ou** [comment]
Thanks for the suggestion. It should be possible to add an option to not separate by date.

**Comment by samuelalexmclean** [comment]
+1 - I'd like to just have bundles + everything else.

**Comment by ukjaybrat** [comment]
+1 - great app. this is one of my biggest issues so far (and it's such a small issue)

**Comment by samuelalexmclean** [comment]
Teresa - would you entertain a pull on this if I had a go? I can imagine there are more important things on your todo list and this one looks like something I could puzzle through.

**Comment by teresa-ou** [comment]
@samuelalexmclean Yes, go for it!

**Comment by benoror** [comment]
Hi! You can turn off **Group messages by date** in Options. Bundles stay; TODAY/YESTERDAY dividers go away.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Site: https://inbundly.com/
