### ISSUE TITLE
Ampersand in label + "View all" option

### ISSUE THREAD

**Issue by adamistic** [teresa-ou/inboxy#44]
Hi -- I have an "A&E" label that I use for arts and entertainment-type messages.

When I click on "View all" in the A&E bundle, it takes me to this Gmail search:

      label:Inbox label:A&E

...but that search returns no results.  However, when I add the quotes, it finds the relevant messages:

      label:Inbox label:"A&E"

Figured it was worth a report.

Thanks for this amazing extension!

**Comment by vtexperts** [comment]
Same for "!".

**Comment by teresa-ou** [comment]
Thanks for letting me know!

**Comment by teresa-ou** [comment]
Fixed in v1.5.1

**Comment by benoror** [comment]
Hi! Labels with `&` needing quotes in **View all** may still be sharp. Please retest on **Inbundly** and open a bug if `label:"A&E"` is not generated automatically.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new
