### ISSUE TITLE
Formatting Issue (Centered/Cutoff)

### ISSUE THREAD

**Issue by dburns103** [teresa-ou/inboxy#45]
Hello,

I have all the preferred settings chosen, but everything is oddly centered and cutoff. I tried to attach screenshots. Any thoughts?

Love the idea behind this! Missed bundling from Google Inbox.

Best,
Danny

![image](https://user-images.githubusercontent.com/67109039/85028229-b6d4aa00-b172-11ea-81b1-4989fca1fc07.png)
![Annotation 2020-06-18 144828](https://user-images.githubusercontent.com/67109039/85028303-ceac2e00-b172-11ea-816e-46e27cbb8b1d.png)

**Comment by teresa-ou** [comment]
Hi @dburns103, were you able to resolve the formatting problem? I see that you closed this Github issue.

**Comment by dburns103** [comment]
Hey there,

Yep, it's because I had Gmelius install. I uninstalled Gmelius and that
fixed it.

Thanks,
Danny
