### ISSUE TITLE
Promotion Tab Not Bundled

### ISSUE THREAD

**Issue by dburns103** [teresa-ou/inboxy#47]
Hello,

I've been using Inboxy for a few days. It had been working great and suddenly it's no longer working for the Promotions tab. The Social tab is still working. Seems like a strange bug. Any thoughts on how to fix it? I have made sure I'm using all the preferred settings. I've attached screenshots below.

Best,
Danny

![image](https://user-images.githubusercontent.com/67109039/85871601-8c17d080-b7c6-11ea-960b-c8977c80e35c.png)

![image](https://user-images.githubusercontent.com/67109039/85871618-95a13880-b7c6-11ea-899f-36667634de56.png)

**Comment by vtexperts** [comment]
I'm having the same issue. Started today or yesterday

**Comment by teresa-ou** [comment]
Thanks for reporting this! I personally don't use tabs, so I hadn't noticed. 

Something might have changed in Gmail's DOM structure recently, so that inboxy is now grabbing the wrong elements on the page in the Promotions tab. I have a pretty good idea about how to fix this.

**Comment by dburns103** [comment]
Of course. Thanks for the help and let me know if you need anything else
from me.

**Comment by teresa-ou** [comment]
Fixed in v1.5.1

**Comment by dburns103** [comment]
Awesome. Thanks so much. Seems like still v1.5.0 in the store
<https://chrome.google.com/webstore/detail/inboxy-inbox-bundles-for/clahkkinbdcdnogkkgmacmiknnamahha>.
Will it update automatically for me or do I need to reinstall when it's
available?

**Comment by teresa-ou** [comment]
It's still pending review, which usually takes a day or so. Once 1.5.1 is published in the store, your browser will update the extension automatically for you.
