### ISSUE TITLE
Archive all messages in a bundle without needing to open it first

### ISSUE THREAD

**Issue by teresa-ou** [teresa-ou/inboxy#5]
User feedback:

"One thing that would be nice is if you could archive all messages in a bundle without clicking to open the bundle first (like having the "mark all as done" button appear when you hover over the bundle). I think in Inbox you could also do that for each time period section"

**Comment by teresa-ou** [comment]
Added the button for both the closed bundle and the date header row in [v1.3.0](https://github.com/teresa-ou/inboxy/releases/tag/v1.3.0)

**Comment by benoror** [comment]
Hi! This shipped (and Inbundly turns **archive-all** on by default). Hover/row control archives the bundle's threads without opening it first. There is also **select-all** and **snooze whole bundle**.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Firefox: https://addons.mozilla.org/firefox/addon/inbundly/
Site: https://inbundly.com/
