### ISSUE TITLE
Delay showing promotions label

### ISSUE THREAD

**Issue by glenviewjeff** [teresa-ou/inboxy#54]
If I remember correctly, Google Inbox would only present the promotions bundle once a day, rather than bother you every time a new email popped up. It would be great if you could implement this feature as well. 

Thanks so much for bringing back bundles!

**Comment by teresa-ou** [comment]
Thanks for your suggestion! It's always helpful to hear about Google Inbox capabilities, since I mostly used the defaults when I was using Inbox.

There is additional discussion in #35, which encompasses this request, so I'll close this issue.

**Comment by benoror** [comment]
Hi! Delayed/scheduled appearance of a Promotions-style bundle is not built. Closest: **snooze whole bundle** (v4.3.0). Please open a schedule-delivery request if you want Inbox-style batching.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new
