### ISSUE TITLE
"Sweeping" a time segment should ignore starred emails

### ISSUE THREAD

**Issue by SteveShaffer** [teresa-ou/inboxy#66]
IIRC in Inbox, when you clicked on the "sweep" button for a time segment (e.g. Today, Yesterday, This Month) it would archive everything **except** starred ("pinned") messages.

![image](https://user-images.githubusercontent.com/877953/88720269-70f7f380-d0d9-11ea-97d4-4277238ded25.png)

That was really useful for going through a day, pinning everything to follow up on, and throwing everything else away.  As best I can tell, the current Inboxy behavior includes starred messages and archives them too, which doesn't support this workflow.

**Comment by SteveShaffer** [comment]
Nevermind.  Duplicate with #25

**Comment by benoror** [comment]
Hi! Date-section "sweep but keep starred" is not implemented (same family as archive-all skipping stars). Please open a feature request on Inbundly if you still want Inbox-style sweep.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new
