### ISSUE TITLE
Can't use Inboxy on the "Important" view?

### ISSUE THREAD

**Issue by jameselson** [teresa-ou/inboxy#68]
Hi,  

I'm so pleased to have bundles back. Thank you!  In the meantime, I've been aggressively training Gmail which emails I think are important. However, as soon as email is filtered to only "Important" (either through search or using the left menu entry), all bundling goodness disappears. 

Would it be possible to support Inboxy on the important view?

  James

**Comment by teresa-ou** [comment]
Hi James, thanks for your feedback! 

It should be possible to add this capability. This sounds like it would be a pretty common use case, so I'm hoping to work on it soon. The solution would be the same as for #32, so I'll close this issue.

**Comment by benoror** [comment]
Hi! **Inbundly** v3.2.0 bundles non-default inbox types and sections, including Important-oriented layouts. Please try the latest build.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Site: https://inbundly.com/
