### ISSUE TITLE
Pinned messages filter/toggle

### ISSUE THREAD

**Issue by teresa-ou** [teresa-ou/inboxy#7]
User feedback:

"I really miss that Inbox had that pin switch button that went to all your pinned (or starred) messages that were in the inbox. In Gmail, to do the same thing, you have to search "is:starred label:inbox". (Pressing the starred button in the side panel includes archived messages)."

**Comment by teresa-ou** [comment]
Added this in v1.4.0

**Comment by benoror** [comment]
Hi! The **pinned (starred in inbox) toggle** is still there in **Inbundly**, and starred messages stay outside bundles by default. You can hide the toggle under Options if you prefer.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Site: https://inbundly.com/
