### ISSUE TITLE
Settings interface

### ISSUE THREAD

**Issue by samuelalexmclean** [teresa-ou/inboxy#72]
There are a few things I'd love to be able to customize (e.g: remove the "This Month", "Last Month" groups and just use bundles; remove [the option to sweep / bulk archive a label](https://user-images.githubusercontent.com/216339/46987785-90cd4b80-d0ed-11e8-83fe-acd6e8de05ab.png) once it contains more than N entries... stuff like that). I don't think any of these changes make sense as defaults.

There's a tricky line to walk here, because "support every use case via a 50 item settings matrix" is a recipe for disaster. But I think there are some situations (the temporal bundles is a good one) where it would be genuinely helpful to support both, because large chunks of people approach this with different mental models.

Would you consider a settings page, maybe just with a version number and link to the Inboxy site for starters, that we could eventually build out to support basic user settings changes?

**Comment by teresa-ou** [comment]
Hi, thanks for sharing your ideas! A settings page actually does exist; there just isn't a whole lot of options available yet. You can access it by clicking on the extension icon, then choosing "Options."

![image](https://user-images.githubusercontent.com/5694027/90458106-4b478400-e0b2-11ea-8e2f-b2eaa8df2a35.png)

**Comment by samuelalexmclean** [comment]
Is there any better response to a feature request than closed, already implemented? Thanks a mil!

I did go looking for this before I posted, but couldn't see an extension icon. I should just be looking near the address bar with all my other extensions chips, right? Is it a recent addition? I'm a few months behind head.

**Comment by samuelalexmclean** [comment]
Weird - I'm running 1.5.1, looks like you added the dialog back in 1.5.0. No sign of it.

With a little digging I can view the page at chrome-extension://foobar/options/options.html which is good enough for me 👍 

Thanks again!

**Comment by teresa-ou** [comment]
Chrome made a recent change where there's an extension menu by default. (There are screenshots at https://www.howtogeek.com/437624/how-to-enable-google-chromes-new-extensions-menu/, although this article is from a year ago). You might not see the inboxy extension icon near the address bar unless you've pinned the extension. 

You probably already know this, but I just thought I would mention it -- if you install the extension via the Chrome Web Store, your browser will automatically update extensions for you.

**Comment by samuelalexmclean** [comment]
Ah - that's got it, thanks! Poor Inboxy was my only extension that made it into the overflow :'( Would love to get onto the auto updates train soon but (for now) I'm stuck on the homebrew version. It's a long story that I won't bore you with ;)

Thanks again!

**Comment by benoror** [comment]
Hi! Options grew a lot in **Inbundly** (grouped sections, autosave, sync/backup). If a specific control is still missing, open a request.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Site: https://inbundly.com/
