### ISSUE TITLE
Compatibility with Simplify v2?

### ISSUE THREAD

**Issue by leggett** [teresa-ou/inboxy#73]
Hi Teresa -- if you want to be in the Simplify v2 beta so you can maintain compatibility with Simplify when v2 launches, would you shoot me an email at hi@simpl.fyi? Thanks!

**Comment by teresa-ou** [comment]
Thanks, I just sent you an email!

**Comment by sttts** [comment]
+1 to wake up this topic. Simplify v2 gets nearer to completion and I don't want to give up on Simplify or Inboxy.

**Comment by leggett** [comment]
Hi Teresa, have you been using the v2 beta? Have you tested compatibility with Simplify v2? I'm launching today.

**Comment by leggett** [comment]
I made the following adjustments. I am hiding my date grouping in the Inbox when Inboxy is enabled. Simplify's date grouping is still applied everywhere else as it appears to be only applied in the inbox.

The .pinned-toggle overlaps with pagination with Simplify enabled. Below is what I did (this is SCSS). Let me know if you do something different and I will remove or change my overrides. 


```
html.simplify.inboxy {
    &:not(.vPane) {
        .pinned-toggle {
            position: fixed;
            right: calc(var(--width-addOns) + 84px);
        }
    }
    &.vPane,
    &.appMenuOpen {
        .pinned-toggle {
            display: none;
    }
}
```

**Comment by teresa-ou** [comment]
Hi all, sorry for the late reply! 

Yes, I have been using the Simplify v2 beta. I'm planning to release a new version of inboxy later today, or tomorrow at the latest.

@leggett Thanks for putting in those overrides -- I did have something else, but will probably remove it (it wasn't a very clean solution)

**Comment by teresa-ou** [comment]
I've pushed v1.6.1 here and submitted it to Chrome & Firefox.

**Comment by sttts** [comment]
@teresa-ou thanks for your great work! Your extension makes a difference for many of us every single day.

**Comment by teresa-ou** [comment]
@sttts Thank you, happy to hear that! 🙂
