### ISSUE TITLE
Mark all as read when clicking "checks?"

### ISSUE THREAD

**Issue by glenviewjeff** [teresa-ou/inboxy#74]
It would be great if you could optionally mark all messages in the bundle as read at the same time they are archived. I end up having to go select all in the label and mark as read later on.

Thanks for the fantastic extension!

**Comment by rcrogers** [comment]
Duplicate of https://github.com/teresa-ou/inboxy/issues/56?

**Comment by glenviewjeff** [comment]
> Duplicate of #56?

Apparently so :)

**Comment by benoror** [comment]
Hi! Optional mark-all-as-read together with archive-all is not built yet. Use **select-all** then Mark as read, or open a feature request.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new

**Comment by glenviewjeff** [comment]
Someone seems to be having fun with LLMs.
