### ISSUE TITLE
Gmail keyboard shortcuts don't work with bundles

### ISSUE THREAD

**Issue by CaneRaiser** [teresa-ou/inboxy#77]
I do a lot of keyboard navigation, and did even more back when I was using Inbox.  When I try to use the standard navigation keystrokes to move within my inbox or open a bundle, they stop working when I encounter a bundle.  If I move down the inbox to the first bundle and press enter, it doesn't open the bundle, it opens one of the messages in it,  When I try to use them to navigate within the bundle they don't work at all.  

Expected behavior: left / right arrows or j / k would move up and down the list by messages.  If enter is pressed on a bundle, that bundle opens and allows navigation in the same way within the bundle.  If the bundle is selected and an action key (like e for archive) is pressed, it acts on the whole bundle.

**Comment by CaneRaiser** [comment]
Just realized this is already covered by #48

**Comment by benoror** [comment]
Hi! Keyboard navigation around bundles is still a weak spot (see also open #48 / #82). **Inbundly** welcomes a fresh, detailed keyboard issue if this blocks you.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new
