### ISSUE TITLE
Bundle Name/Unread-Sender is overlapping 

### ISSUE THREAD

**Issue by vtexperts** [teresa-ou/inboxy#9]
I use subfolders and some of them tend to have longer names, which results in overlap.
![chrome_2020-03-30_07-25-04 1](https://user-images.githubusercontent.com/17834854/77912317-f36dc500-7257-11ea-8466-cac473d0dd42.png)

**Comment by teresa-ou** [comment]
Sorry about that! It should be fixed in v1.2.1. The longer names will wrap instead of overlapping.
